### ISSUE TITLE
How to get authorized via shell script?

### ISSUE THREAD

**Issue by indaco** [mlenkeit/sap-hcp-express-proxy#1]
Hi Maximilian,
your project is really helpful as well the nodejs module by @gregorwolf . They avoid me some development time simply because they work as is, in just few seconds!

What I'm trying to do now is, after the server is running, call the basic auth via shell with wget or curl in order to be authorized on my raspberrypi (no gui and so no browser) and then be able to call the xsjs service.

Below the wget command I use:

``` Batchfile
wget --save-cookies cookies.txt --post-data "name=myname&pass=mypass" http://localhost:port/myTrialUser/pack/to/service.xsjs
```

The response is always the same: 401 Unauthorized

How can I do on the raspberrypi? Any advice?
I don't know if you see issues opened on @gregorwolf repos, so I prefer post here the same question - https://github.com/gregorwolf/hanatrial-auth-proxy/issues/9 

I apologize for the duplicate
Thanks a lot. Any help is really appreciate.

**Comment by indaco** [comment]
I solved the issue using the following wget syntax

``` Batchfile
wget --http-user=myname --http-password=mypass" http://localhost:port/myTrialUser/pack/to/service.xsjs
```

If you think I can accomplish it better in my scenario, please let me know.
Thanks a lot and sorry for the spam.

**Comment by mlenkeit** [comment]
I've been thinking about supporting something like the following:

``` javascript
app.use('/hcp', hcpProxy(hcpHost, {
  auth: {
    user: 'myHcpUser',
    password: 'myHcpPassword'
  }
}));
```

This would directly authenticate with the given credentials against HCP.

@indaco Would this be helpful?

/cc @gregorwolf

**Comment by indaco** [comment]
@mlenkeit it should be great and let me say, it really makes sense :-)

I'm ready to test it ;-)

Thanks for your help.

**Comment by gregorwolf** [comment]
For a command line client there is an example coming with the https://github.com/gregorwolf/hanatrial-auth-proxy project in the file: https://github.com/gregorwolf/hanatrial-auth-proxy/blob/master/examples/saml-client.js
